### ISSUE TITLE
Generate average `budget.DeviceDailyCarbonFootprint` objects for dates when we have no incoming data

### ISSUE THREAD

**Issue by juyrjola** [kausaltech/mocaf#4]
We will use the `bronze` level daily carbon footprint to compensate for the dates when the user has either disabled Mocaf or no valid data (`trips_ingest.Location` or `trips_ingest.DeviceHeartbeat`) is received. This way we will not give prizes for users that do not use Mocaf.

It should probably be done in `trips.models.Device.update_daily_carbon_footprint()`. We now have `DeviceDailyCarbonFootprint.average_footprint_used` field to indicate that the average was used instead of actual data.

In the monthly Celery task where we will determine the prize levels, we probably should run `update_daily_carbon_footprint()` for all devices to ensure no gaps in daily footprints remain.

**Comment by bbliem** [comment]
Should be done in f9b1f5ca5404a2bb91759228b90212251b17aa28 and 6a119c13c612aa831d1c860b30ec99515f4b70b1.
